### PR TITLE
no more 0 ping clicks since they ban

### PR DESCRIPTION
**Pull request by OctoSplash01**
aaaaaaaaaaaaaaaaaaaaaaaaaaa

### CODE REVIEW

**Comment by ghost** [comment]
@night0721

**Review by PerchunPak — COMMENTED** [review]
This just decreases speed of clicks. It anyway can trigger pingless click, if you have a big ping.

The real fix should be done only after research what "pingless click" actually is (just ask it somewhere in cheat dev community ig).

**Comment by OctoSplash01** [comment]
it doesnt decrease the speed of clicks. IT MAKES IT NOT CLICK IN A NON EXISTANT WINDOW ID. GO FUCKING EDUCATE YOURSELF before talking to me.

FROM: clickWindow(Lilase.mc.thePlayer.openContainer.windowId + 1, 31);
TO: clickWindow(Lilase.mc.thePlayer.openContainer.windowId, 31);
^ this makes it not be a pingless click please again go educate yourself

**Comment by Cephetir** [comment]
Damn bro that's crazy drama out here

**Comment by hy-mp3** [comment]
@night0721

**Comment by night0721** [comment]
What

**Comment by hy-mp3** [comment]
> What

merge & compile

**Comment by ghost** [comment]
# For the sake of users safety please merge
Lilase is currently banning players

**Comment by night0721** [comment]
bro deleted the whole master branch?????????????

**Comment by ghost** [comment]
i accidentally removed master branch but i restored it

**Comment by night0721** [comment]
wtf is the gradle.yml @OctoSplash01 @Gabagooooooooooool

**Comment by ghost** [comment]
Sorry for so much things here, but octo tried to compile the mod, and his local gradle wasnt working so he tried to use other m method xd. This wont happen again @night0721

**Comment by ghost** [comment]
I removed it already

**Pull request closed without merging**
